[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'leico/autodate.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'olimorris/onedarkpro.nvim'

[[plugins]]
repo = 'github/copilot.vim'


[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'


[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
	nnoremap <silent><C-n> :Fern . -reveal=% -drawer -toggle -width=35<CR>
	let g:fern#renderer='nerdfont'
	'''

[[plugins]]
repo = 'tpope/vim-fugitive'
